'use strict';
module.exports = {
  root: true,
  env: {
    browser: true,
    jest: true,
    node: true
  },
  overrides: [
    {
      files: [ "*.ts" ],
	  plugins: [ "@typescript-eslint", "no-loops", "no-secrets", "no-unsanitized", "promise", "unused-imports", "xss" ],
      parser: "@typescript-eslint/parser",
      parserOptions: {
        project: [
          "tsconfig.json"
        ],
		createDefaultProgram: true,
        sourceType: "module",
        ecmaVersion: 2015,
        ecmaFeatures: {
          jsx: true
        }
      },
      rules: {
        "for-direction": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-await-in-loop": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-console": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "off",
        "no-empty-character-class": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-extra-parens": "off",
        "no-extra-semi": "error",
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "off",
        "no-misleading-character-class": "error",
        "no-obj-calls": "error",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-regex-spaces": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-useless-backreference": "error",
        "require-atomic-updates": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "accessor-pairs": "error",
        "array-callback-return": "error",
        "block-scoped-var": "error",
        "class-methods-use-this": "off",
        "complexity": "error",
        "consistent-return": "error",
        "curly": "error",
        "default-case": "warn",
        "default-case-last": "error",
        "default-param-last": "off",
        "dot-location": [ "error", "property" ],
        "dot-notation": "off",
        "eqeqeq": "error",
        "grouped-accessor-pairs": "warn",
        "guard-for-in": "warn",
        "max-classes-per-file": [ "error", 1 ],
        "no-alert": "error",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-constructor-return": "error",
        "no-div-regex": "error",
        "no-else-return": "error",
        "no-empty-function": "off",
        "no-empty-pattern": "warn",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-label": "error",
        "no-fallthrough": "error",
        "no-floating-decimal": "off",
        "no-global-assign": "error",
        "no-implicit-coercion": "off",
        "no-implicit-globals": "error",
        "no-implied-eval": "off",
        "no-invalid-this": "off",
        "no-iterator": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-loop-func": "off",
        "no-magic-numbers": "off",
        "no-multi-spaces": "error",
        "no-multi-str": "warn",
        "no-new": "off",
        "no-new-func": "error",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-param-reassign": "error",
        "no-proto": "error",
        "no-redeclare": "off",
        "no-restricted-properties": "off",
        "no-return-assign": "error",
        "no-return-await": "off",
        "no-script-url": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-throw-literal": "off",
        "no-unmodified-loop-condition": "error",
        "no-unused-expressions": "off",
        "no-unused-labels": "error",
        "no-useless-call": "error",
        "no-useless-catch": "error",
        "no-useless-concat": "error",
        "no-useless-escape": "error",
        "no-useless-return": "error",
        "no-void": "error",
        "no-warning-comments": "warn",
        "no-with": "error",
        "prefer-named-capture-group": "off",
        "prefer-promise-reject-errors": "off",
        "prefer-regex-literals": "off",
        "radix": "error",
        "require-await": "off",
        "require-unicode-regexp": "warn",
        "vars-on-top": "off",
        "wrap-iife": "off",
        "yoda": "warn",
        "strict": "off",
        "init-declarations": "off",
        "no-delete-var": "error",
        "no-label-var": "error",
        "no-restricted-globals": "off",
        "no-shadow": "off",
        "no-shadow-restricted-names": "error",
        "no-undef": "off",
        "no-undef-init": "error",
        "no-undefined": "off",
        "no-unused-vars": "off",
        "no-use-before-define": "off",
        "array-bracket-newline": "off",
        "array-bracket-spacing": [ "error", "never" ],
        "array-element-newline": "off",
        "block-spacing": "error",
        "brace-style": "off",
        "camelcase": "warn",
        "capitalized-comments": "error",
        "comma-dangle": "off",
        "comma-spacing": "off",
        "comma-style": "error",
        "computed-property-spacing": "error",
        "consistent-this": "error",
        "eol-last": "error",
        "func-call-spacing": "off",
        "func-name-matching": "off",
        "func-names": "error",
        "func-style": "error",
        "function-call-argument-newline": "off",
        "function-paren-newline": "off",
        "id-denylist": "off",
        "id-length": [
          "error",
          {
            "min": 2,
            "max": 24,
            "exceptionPatterns": [ "_", "\\$[a-z]+" ]
          }
        ],
        "id-match": "off",
        "implicit-arrow-linebreak": "off",
        "indent": [ "off", "tab" ],
        "jsx-quotes": "error",
        "key-spacing": "error",
        "keyword-spacing": "off",
        "line-comment-position": "error",
        "linebreak-style": "off",
        "lines-around-comment": "error",
        "lines-between-class-members": [
          "off",
          "always",
          { "exceptAfterSingleLine": true }
        ],
        "max-depth": [ "error", 3 ],
        "max-len": [
          "error",
          {
            "code": 120,
            "ignoreComments": true
          }
        ],
        "max-lines": [ "error", 100 ],
        "max-lines-per-function": [ "error", 35 ],
        "max-nested-callbacks": [ "error", 3 ],
        "max-params": [ "error", 4 ],
        "max-statements": [ "error", 20 ],
        "max-statements-per-line": "error",
        "multiline-ternary": "off",
        "new-cap": "error",
        "new-parens": "error",
        "newline-per-chained-call": [
          "error",
          { "ignoreChainWithDepth": 2 }
        ],
        "no-array-constructor": "off",
        "no-bitwise": "error",
        "no-continue": "off",
        "no-lonely-if": "error",
        "no-mixed-operators": "off",
        "no-mixed-spaces-and-tabs": "off",
        "no-multi-assign": "error",
        "no-multiple-empty-lines": "error",
        "no-negated-condition": "error",
        "no-nested-ternary": "off",
        "no-new-object": "error",
        "no-plusplus": "off",
        "no-restricted-syntax": "off",
        "no-tabs": "off",
        "no-ternary": "off",
        "no-trailing-spaces": "error",
        "no-underscore-dangle": "off",
        "no-unneeded-ternary": "error",
        "no-whitespace-before-property": "error",
        "nonblock-statement-body-position": [ "error", "below" ],
        "object-curly-newline": "off",
        "object-curly-spacing": "off",
        "object-property-newline": [
          "error",
          { "allowAllPropertiesOnSameLine": true }
        ],
        "one-var": "off",
        "one-var-declaration-per-line": "off",
        "operator-assignment": "error",
        "operator-linebreak": "off",
        "padded-blocks": [ "error", "never" ],
        "padding-line-between-statements": "off",
        "prefer-exponentiation-operator": "off",
        "prefer-object-spread": "off",
        "quote-props": [ "error", "as-needed" ],
        "quotes": "off",
        "semi": "off",
        "semi-spacing": "error",
        "semi-style": "off",
        "sort-keys": "off",
        "sort-vars": "off",
        "space-before-blocks": "error",
        "space-before-function-paren": "off",
        "space-in-parens": "error",
        "space-infix-ops": "off",
        "space-unary-ops": "error",
        "spaced-comment": "error",
        "switch-colon-spacing": "error",
        "template-tag-spacing": "error",
        "unicode-bom": "off",
        "wrap-regex": "off",
        "arrow-body-style": [
          "error",
          "as-needed",
          { "requireReturnForObjectLiteral": true }
        ],
        "arrow-parens": [
          "error",
          "as-needed",
          { "requireForBlockBody": false }
        ],
        "arrow-spacing": "error",
        "constructor-super": "error",
        "generator-star-spacing": "error",
        "no-class-assign": "error",
        "no-confusing-arrow": "error",
        "no-const-assign": "error",
        "no-dupe-class-members": "off",
        "no-duplicate-imports": "off",
        "no-new-symbol": "error",
        "no-restricted-exports": "off",
        "no-restricted-imports": "off",
        "no-this-before-super": "error",
        "no-useless-computed-key": "error",
        "no-useless-constructor": "off",
        "no-useless-rename": "error",
        "no-var": "error",
        "object-shorthand": "error",
        "prefer-arrow-callback": "error",
        "prefer-const": "error",
        "prefer-destructuring": "off",
        "prefer-numeric-literals": "warn",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "prefer-template": "error",
        "require-yield": "error",
        "sort-imports": "off",
        "symbol-description": "error",
        "template-curly-spacing": "error",
        "yield-star-spacing": "error",
        "no-loops/no-loops": 2,
        "no-secrets/no-secrets": [
          "error",
          { "ignoreContent": [ "__zone_symbol__UNPATCHED_EVENTS" ] }
        ],
        "no-unsanitized/method": "error",
        "no-unsanitized/property": "error",
        "promise/always-return": "error",
        "promise/no-return-wrap": [
          "error",
          { "allowReject": true }
        ],
        "promise/param-names": "error",
        "promise/catch-or-return": [
          "error",
          {
            "allowThen": true,
            "terminationMethod": [ "catch", "finally" ]
          }
        ],
        "promise/no-native": "off",
        "promise/no-nesting": "off",
        "promise/no-promise-in-callback": "off",
        "promise/no-callback-in-promise": "off",
        "promise/avoid-new": "warn",
        "promise/no-new-statics": "error",
        "promise/no-return-in-finally": "warn",
        "promise/valid-params": "warn",
        "unused-imports/no-unused-imports": "error",
        "unused-imports/no-unused-vars": [
          "warn",
          {
            "vars": "all",
            "varsIgnorePattern": "^_",
            "args": "after-used",
            "argsIgnorePattern": "^_"
          }
        ],
        "xss/no-mixed-html": [
          2,
          {
            "htmlVariableRules": [ "AsHtml", "HtmlEncoded/i", "^html$" ],
            "htmlFunctionRules": [ ".asHtml/i", "toHtml" ],
            "functions": {
              "$": {
                "htmlInput": true,
                "safe": [ "document", "this" ]
              },
              ".html": {
                "htmlInput": true,
                "htmlOutput": true
              },
              ".join": {
                "passthrough": {
                  "obj": true,
                  "args": true
                }
              }
            }
          }
        ],
        "xss/no-location-href-assign": [
          2,
          {
            "escapeFunc": "escapeHref"
          }
        ],
        "@typescript-eslint/brace-style": [ "error" ],
        "@typescript-eslint/comma-dangle": [ "error", "never" ],
        "@typescript-eslint/comma-spacing": [ "error" ],
        "@typescript-eslint/default-param-last": [ "error" ],
        "@typescript-eslint/dot-notation": [ "error" ],
        "@typescript-eslint/func-call-spacing": [ "error" ],
        "@typescript-eslint/indent": [ "off", "tab" ],
        "@typescript-eslint/init-declarations": [ "off" ],
        "@typescript-eslint/keyword-spacing": [ "error" ],
        "@typescript-eslint/lines-between-class-members": [
          "error",
          "always",
          { "exceptAfterSingleLine": true }
        ],
        "@typescript-eslint/no-array-constructor": [ "error" ],
        "@typescript-eslint/no-dupe-class-members": [ "error" ],
        "@typescript-eslint/no-duplicate-imports": [ "error" ],
        "@typescript-eslint/no-empty-function": [ "error" ],
        "@typescript-eslint/no-extra-parens": [ "error" ],
        "@typescript-eslint/no-extra-semi": [ "error" ],
        "@typescript-eslint/no-implied-eval": [ "error" ],
        "@typescript-eslint/no-invalid-this": [ "error" ],
        "@typescript-eslint/no-loop-func": [ "error" ],
        "@typescript-eslint/no-loss-of-precision": [ "error" ],
        "@typescript-eslint/no-magic-numbers": [
          "error",
          {
            "ignore": [ 0, 1 ],
            "ignoreArrayIndexes": true,
            "ignoreDefaultValues": true,
            "ignoreEnums": true,
            "ignoreReadonlyClassProperties": true,
            "enforceConst": true
          }
        ],
        "@typescript-eslint/no-redeclare": [ "error" ],
        "@typescript-eslint/no-shadow": [ "error" ],
        "@typescript-eslint/no-throw-literal": [ "error" ],
        "@typescript-eslint/no-unused-expressions": [ "error" ],
        "@typescript-eslint/no-unused-vars": [
          "error",
          { "argsIgnorePattern": "^_" }
        ],
        "@typescript-eslint/no-use-before-define": [ "error" ],
        "@typescript-eslint/no-useless-constructor": [ "error" ],
        "@typescript-eslint/object-curly-spacing": [ "error", "always" ],
        "@typescript-eslint/quotes": [
          "error",
          "single",
          { "allowTemplateLiterals": true }
        ],
        "@typescript-eslint/require-await": [ "error" ],
        "@typescript-eslint/return-await": [ "error" ],
        "@typescript-eslint/semi": [ "error" ],
        "@typescript-eslint/space-before-function-paren": [ "error", "never" ],
        "@typescript-eslint/space-infix-ops": [ "error" ]
      }
    },
    {
      files: [ "*.vue" ],
	  plugins: [ "@typescript-eslint", "vue" ],
      parser: "vue-eslint-parser",
      parserOptions: {
        parser: "@typescript-eslint/parser",
        project: [
          "tsconfig.json"
        ],
		createDefaultProgram: true,
        sourceType: "module",
        ecmaVersion: 2015,
        ecmaFeatures: {
          jsx: true
        }
      },
      rules: {
        "for-direction": "error",
        "getter-return": "error",
        "no-async-promise-executor": "error",
        "no-await-in-loop": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-console": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "off",
        "no-empty-character-class": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-extra-parens": "off",
        "no-extra-semi": "error",
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "off",
        "no-misleading-character-class": "error",
        "no-obj-calls": "error",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-regex-spaces": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-useless-backreference": "error",
        "require-atomic-updates": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "accessor-pairs": "error",
        "array-callback-return": "error",
        "block-scoped-var": "error",
        "class-methods-use-this": "off",
        "complexity": "error",
        "consistent-return": "error",
        "curly": "error",
        "default-case": "warn",
        "default-case-last": "error",
        "default-param-last": "off",
        "dot-location": [ "error", "property" ],
        "dot-notation": "off",
        "eqeqeq": "error",
        "grouped-accessor-pairs": "warn",
        "guard-for-in": "warn",
        "max-classes-per-file": [ "error", 1 ],
        "no-alert": "error",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-constructor-return": "error",
        "no-div-regex": "error",
        "no-else-return": "error",
        "no-empty-function": "off",
        "no-empty-pattern": "warn",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-label": "error",
        "no-fallthrough": "error",
        "no-floating-decimal": "off",
        "no-global-assign": "error",
        "no-implicit-coercion": "off",
        "no-implicit-globals": "error",
        "no-implied-eval": "off",
        "no-invalid-this": "off",
        "no-iterator": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-loop-func": "off",
        "no-magic-numbers": "off",
        "no-multi-spaces": "error",
        "no-multi-str": "warn",
        "no-new": "off",
        "no-new-func": "error",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-param-reassign": "error",
        "no-proto": "error",
        "no-redeclare": "off",
        "no-restricted-properties": "off",
        "no-return-assign": "error",
        "no-return-await": "off",
        "no-script-url": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-throw-literal": "off",
        "no-unmodified-loop-condition": "error",
        "no-unused-expressions": "off",
        "no-unused-labels": "error",
        "no-useless-call": "error",
        "no-useless-catch": "error",
        "no-useless-concat": "error",
        "no-useless-escape": "error",
        "no-useless-return": "error",
        "no-void": "error",
        "no-warning-comments": "warn",
        "no-with": "error",
        "prefer-named-capture-group": "off",
        "prefer-promise-reject-errors": "off",
        "prefer-regex-literals": "off",
        "radix": "error",
        "require-await": "off",
        "require-unicode-regexp": "warn",
        "vars-on-top": "off",
        "wrap-iife": "off",
        "yoda": "warn",
        "strict": "off",
        "init-declarations": "off",
        "no-delete-var": "error",
        "no-label-var": "error",
        "no-restricted-globals": "off",
        "no-shadow": "off",
        "no-shadow-restricted-names": "error",
        "no-undef": "off",
        "no-undef-init": "error",
        "no-undefined": "off",
        "no-unused-vars": "off",
        "no-use-before-define": "off",
        "array-bracket-newline": "off",
        "array-bracket-spacing": [ "error", "never" ],
        "array-element-newline": "off",
        "block-spacing": "error",
        "brace-style": "off",
        "camelcase": "warn",
        "capitalized-comments": "error",
        "comma-dangle": "off",
        "comma-spacing": "off",
        "comma-style": "error",
        "computed-property-spacing": "error",
        "consistent-this": "error",
        "eol-last": "error",
        "func-call-spacing": "off",
        "func-name-matching": "off",
        "func-names": "error",
        "func-style": "error",
        "function-call-argument-newline": "off",
        "function-paren-newline": "off",
        "id-denylist": "off",
        "id-length": [
          "error",
          {
            "min": 2,
            "max": 24,
            "exceptionPatterns": [ "_", "\\$[a-z]+" ]
          }
        ],
        "id-match": "off",
        "implicit-arrow-linebreak": "off",
        "indent": [ "off", "tab" ],
        "jsx-quotes": "error",
        "key-spacing": "error",
        "keyword-spacing": "off",
        "line-comment-position": "error",
        "linebreak-style": "off",
        "lines-around-comment": "error",
        "lines-between-class-members": [
          "off",
          "always",
          { "exceptAfterSingleLine": true }
        ],
        "max-depth": [ "error", 3 ],
        "max-len": [
          "error",
          {
            "code": 120,
            "ignoreComments": true
          }
        ],
        "max-lines": [ "error", 120 ],
        "max-lines-per-function": [ "error", 35 ],
        "max-nested-callbacks": [ "error", 3 ],
        "max-params": [ "error", 4 ],
        "max-statements": [ "error", 20 ],
        "max-statements-per-line": "error",
        "multiline-ternary": "off",
        "new-cap": "error",
        "new-parens": "error",
        "newline-per-chained-call": [
          "error",
          { "ignoreChainWithDepth": 2 }
        ],
        "no-array-constructor": "off",
        "no-bitwise": "error",
        "no-continue": "off",
        "no-lonely-if": "error",
        "no-mixed-operators": "off",
        "no-mixed-spaces-and-tabs": "off",
        "no-multi-assign": "error",
        "no-multiple-empty-lines": "error",
        "no-negated-condition": "error",
        "no-nested-ternary": "off",
        "no-new-object": "error",
        "no-plusplus": "off",
        "no-restricted-syntax": "off",
        "no-tabs": "off",
        "no-ternary": "off",
        "no-trailing-spaces": "error",
        "no-underscore-dangle": "off",
        "no-unneeded-ternary": "error",
        "no-whitespace-before-property": "error",
        "nonblock-statement-body-position": [ "error", "below" ],
        "object-curly-newline": "off",
        "object-curly-spacing": "off",
        "object-property-newline": [
          "error",
          { "allowAllPropertiesOnSameLine": true }
        ],
        "one-var": "off",
        "one-var-declaration-per-line": "off",
        "operator-assignment": "error",
        "operator-linebreak": "off",
        "padded-blocks": [ "error", "never" ],
        "padding-line-between-statements": "off",
        "prefer-exponentiation-operator": "off",
        "prefer-object-spread": "off",
        "quote-props": [ "error", "as-needed" ],
        "quotes": "off",
        "semi": "off",
        "semi-spacing": "error",
        "semi-style": "off",
        "sort-keys": "off",
        "sort-vars": "off",
        "space-before-blocks": "error",
        "space-before-function-paren": "off",
        "space-in-parens": "error",
        "space-infix-ops": "off",
        "space-unary-ops": "error",
        "spaced-comment": "error",
        "switch-colon-spacing": "error",
        "template-tag-spacing": "error",
        "unicode-bom": "off",
        "wrap-regex": "off",
        "arrow-body-style": [
          "error",
          "as-needed",
          { "requireReturnForObjectLiteral": true }
        ],
        "arrow-parens": [
          "error",
          "as-needed",
          { "requireForBlockBody": false }
        ],
        "arrow-spacing": "error",
        "constructor-super": "error",
        "generator-star-spacing": "error",
        "no-class-assign": "error",
        "no-confusing-arrow": "error",
        "no-const-assign": "error",
        "no-dupe-class-members": "off",
        "no-duplicate-imports": "off",
        "no-new-symbol": "error",
        "no-restricted-exports": "off",
        "no-restricted-imports": "off",
        "no-this-before-super": "error",
        "no-useless-computed-key": "error",
        "no-useless-constructor": "off",
        "no-useless-rename": "error",
        "no-var": "error",
        "object-shorthand": "error",
        "prefer-arrow-callback": "error",
        "prefer-const": "error",
        "prefer-destructuring": "off",
        "prefer-numeric-literals": "warn",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "prefer-template": "error",
        "require-yield": "error",
        "sort-imports": "off",
        "symbol-description": "error",
        "template-curly-spacing": "error",
        "yield-star-spacing": "error",
        "no-loops/no-loops": 2,
        "no-secrets/no-secrets": [
          "error",
          { "ignoreContent": [ "__zone_symbol__UNPATCHED_EVENTS" ] }
        ],
        "no-unsanitized/method": "error",
        "no-unsanitized/property": "error",
        "promise/always-return": "error",
        "promise/no-return-wrap": [
          "error",
          { "allowReject": true }
        ],
        "promise/param-names": "error",
        "promise/catch-or-return": [
          "error",
          {
            "allowThen": true,
            "terminationMethod": [ "catch", "finally" ]
          }
        ],
        "promise/no-native": "off",
        "promise/no-nesting": "off",
        "promise/no-promise-in-callback": "off",
        "promise/no-callback-in-promise": "off",
        "promise/avoid-new": "warn",
        "promise/no-new-statics": "error",
        "promise/no-return-in-finally": "warn",
        "promise/valid-params": "warn",
        "unused-imports/no-unused-imports": "error",
        "unused-imports/no-unused-vars": [
          "warn",
          {
            "vars": "all",
            "varsIgnorePattern": "^_",
            "args": "after-used",
            "argsIgnorePattern": "^_"
          }
        ],
        "xss/no-mixed-html": [
          2,
          {
            "htmlVariableRules": [ "AsHtml", "HtmlEncoded/i", "^html$" ],
            "htmlFunctionRules": [ ".asHtml/i", "toHtml" ],
            "functions": {
              "$": {
                "htmlInput": true,
                "safe": [ "document", "this" ]
              },
              ".html": {
                "htmlInput": true,
                "htmlOutput": true
              },
              ".join": {
                "passthrough": {
                  "obj": true,
                  "args": true
                }
              }
            }
          }
        ],
        "xss/no-location-href-assign": [
          2,
          {
            "escapeFunc": "escapeHref"
          }
        ],
        "@typescript-eslint/brace-style": [ "error" ],
        "@typescript-eslint/comma-dangle": [ "error", "never" ],
        "@typescript-eslint/comma-spacing": [ "error" ],
        "@typescript-eslint/default-param-last": [ "error" ],
        "@typescript-eslint/dot-notation": [ "error" ],
        "@typescript-eslint/func-call-spacing": [ "error" ],
        "@typescript-eslint/indent": [ "off", "tab" ],
        "@typescript-eslint/init-declarations": [ "off" ],
        "@typescript-eslint/keyword-spacing": [ "error" ],
        "@typescript-eslint/lines-between-class-members": [
          "error",
          "always",
          { "exceptAfterSingleLine": true }
        ],
        "@typescript-eslint/no-array-constructor": [ "error" ],
        "@typescript-eslint/no-dupe-class-members": [ "error" ],
        "@typescript-eslint/no-duplicate-imports": [ "error" ],
        "@typescript-eslint/no-empty-function": [ "error" ],
        "@typescript-eslint/no-extra-parens": [ "error" ],
        "@typescript-eslint/no-extra-semi": [ "error" ],
        "@typescript-eslint/no-implied-eval": [ "error" ],
        "@typescript-eslint/no-invalid-this": [ "error" ],
        "@typescript-eslint/no-loop-func": [ "error" ],
        "@typescript-eslint/no-loss-of-precision": [ "error" ],
        "@typescript-eslint/no-magic-numbers": [
          "error",
          {
            "ignore": [ 0, 1 ],
            "ignoreArrayIndexes": true,
            "ignoreDefaultValues": true,
            "ignoreEnums": true,
            "ignoreReadonlyClassProperties": true,
            "enforceConst": true
          }
        ],
        "@typescript-eslint/no-redeclare": [ "error" ],
        "@typescript-eslint/no-shadow": [ "error" ],
        "@typescript-eslint/no-throw-literal": [ "error" ],
        "@typescript-eslint/no-unused-expressions": [ "error" ],
        "@typescript-eslint/no-unused-vars": [
          "error",
          { "argsIgnorePattern": "^_" }
        ],
        "@typescript-eslint/no-use-before-define": [ "error" ],
        "@typescript-eslint/no-useless-constructor": [ "error" ],
        "@typescript-eslint/object-curly-spacing": [ "error", "always" ],
        "@typescript-eslint/quotes": [
          "error",
          "single",
          { "allowTemplateLiterals": true }
        ],
        "@typescript-eslint/require-await": [ "error" ],
        "@typescript-eslint/return-await": [ "error" ],
        "@typescript-eslint/semi": [ "error" ],
        "@typescript-eslint/space-before-function-paren": [ "error", "never" ],
        "@typescript-eslint/space-infix-ops": [ "error" ],
        "vue/comment-directive": [
          "error",
          {
            "reportUnusedDisableDirectives": false
          }
        ],
        "vue/component-api-style": "off",
        "vue/first-attribute-linebreak": "error",
        "vue/jsx-uses-vars": "off",
        "vue/script-setup-uses-vars": "error",
        "vue/multi-word-component-names": "error",
        "vue/no-arrow-functions-in-watch": "error",
        "vue/no-async-in-computed-properties": "error",
        "vue/no-computed-properties-in-data": "error",
        "vue/no-deprecated-router-link-tag-prop": "error",
        "vue/no-deprecated-v-is": "error",
        "vue/no-dupe-keys": "error",
        "vue/no-dupe-v-else-if": "error",
        "vue/no-duplicate-attributes": "error",
        "vue/no-export-in-script-setup": "error",
        "vue/no-loss-of-precision": "error",
        "vue/no-mutating-props": "error",
        "vue/no-parsing-error": "error",
        "vue/no-reserved-keys": "off",
        "vue/no-reserved-props": "error",
        "vue/no-shared-component-data": "error",
        "vue/no-side-effects-in-computed-properties": "error",
        "vue/no-template-key": "error",
        "vue/no-textarea-mustache": "error",
        "vue/no-undef-properties": "error",
        "vue/no-unused-components": "error",
        "vue/no-unused-vars": [
          "error",
          {
            "ignorePattern": "^_"
          }
        ],
        "vue/no-use-v-if-with-v-for": [
          "error",
          {
            "allowUsingIterationVar": true
          }
        ],
        "vue/no-useless-template-attributes": "error",
        "vue/require-component-is": "error",
        "vue/require-prop-type-constructor": "error",
        "vue/require-render-return": "error",
        "vue/require-v-for-key": "error",
        "vue/require-valid-default-prop": "error",
        "vue/return-in-computed-property": "error",
        "vue/use-v-on-exact": [ "error" ],
        "vue/valid-define-emits": "error",
        "vue/valid-define-props": "error",
        "vue/valid-next-tick": "error",
        "vue/valid-template-root": "error",
        "vue/valid-v-bind": "error",
        "vue/valid-v-cloak": "error",
        "vue/valid-v-else-if": "error",
        "vue/valid-v-else": "error",
        "vue/valid-v-for": "error",
        "vue/valid-v-html": "error",
        "vue/valid-v-if": "error",
        "vue/valid-v-is": "error",
        "vue/valid-v-memo": "error",
        "vue/valid-v-model": "error",
        "vue/valid-v-on": "error",
        "vue/valid-v-once": "error",
        "vue/valid-v-pre": "error",
        "vue/valid-v-show": "error",
        "vue/valid-v-slot": "error",
        "vue/valid-v-text": "error",
        "vue/no-deprecated-data-object-declaration": "error",
        "vue/no-deprecated-destroyed-lifecycle": "error",
        "vue/no-deprecated-dollar-listeners-api": "error",
        "vue/no-deprecated-dollar-scopedslots-api": "error",
        "vue/no-deprecated-events-api": "error",
        "vue/no-deprecated-filter": "error",
        "vue/no-deprecated-functional-template": "error",
        "vue/no-deprecated-html-element-is": "error",
        "vue/no-deprecated-inline-template": "error",
        "vue/no-deprecated-props-default-this": "error",
        "vue/no-deprecated-scope-attribute": "error",
        "vue/no-deprecated-slot-attribute": "error",
        "vue/no-deprecated-slot-scope-attribute": "error",
        "vue/no-deprecated-v-bind-sync": "error",
        "vue/no-deprecated-v-on-native-modifier": "error",
        "vue/no-deprecated-v-on-number-modifiers": "error",
        "vue/no-deprecated-vue-config-keycodes": "error",
        "vue/no-lifecycle-after-await": "error",
        "vue/no-ref-as-operand": "error",
        "vue/no-setup-props-destructure": "error",
        "vue/no-v-for-template-key-on-child": "off",
        "vue/no-v-text": "error",
        "vue/no-watch-after-await": "error",
        "vue/require-slots-as-functions": "error",
        "vue/require-toggle-inside-transition": "error",
        "vue/return-in-emits-validator": "error",
        "vue/no-custom-modifiers-on-v-model": "error",
        "vue/no-multiple-template-root": "error",
        "vue/no-v-for-template-key": "error",
        "vue/no-v-model-argument": "error",
        "vue/valid-v-bind-sync": "error",
        "vue/attribute-hyphenation": "error",
        "vue/component-definition-name-casing": "error",
        "vue/html-closing-bracket-newline": [
          "error",
          {
            "singleline": "never",
            "multiline": "never"
          }
        ],
        "vue/html-closing-bracket-spacing": [
          "error",
          {
            "startTag": "never",
            "endTag": "never",
            "selfClosingTag": "always"
          }
        ],
        "vue/html-end-tags": "error",
        "vue/html-indent": [
          "error",
          "tab"
        ],
        "vue/html-quotes": "error",
        "vue/html-self-closing": "off",
        "vue/require-prop-types": "error",
        "vue/max-attributes-per-line": "off",
        "vue/multiline-html-element-content-newline": "off",
        "vue/mustache-interpolation-spacing": [ "error", "always" ],
        "vue/no-multi-spaces": "error",
        "vue/no-spaces-around-equal-signs-in-attribute": "error",
        "vue/no-template-shadow": "error",
        "vue/one-component-per-file": "error",
        "vue/prop-name-casing": "error",
        "vue/require-default-prop": "off",
        "vue/singleline-html-element-content-newline": "off",
        "vue/v-bind-style": "error",
        "vue/v-on-style": "error",
        "vue/v-slot-style": "error",
        "vue/require-explicit-emits": [
          "error",
          {
            "allowProps": false
          }
        ],
        "vue/attributes-order": "off",
        "vue/component-tags-order": [
          "error",
          {
            "order": [
              [ "template", "script" ],
              "style"
            ]
          }
        ],
        "vue/no-lone-template": [ "error" ],
        "vue/no-multiple-slot-args": "error",
        "vue/no-v-html": "error",
        "vue/order-in-components": "error",
        "vue/this-in-template": "error",
        "vue/block-tag-newline": "off",
        "vue/component-name-in-template-casing": [
          "error",
          "kebab-case",
          {
            "registeredComponentsOnly": false
          }
        ],
        "vue/custom-event-name-casing": [
          "error",
          "camelCase"
        ],
        "vue/html-button-has-type": [ "error" ],
        "vue/html-comment-content-newline": "off",
        "vue/html-comment-content-spacing": "off",
        "vue/html-comment-indent": "off",
        "vue/match-component-file-name": "off",
        "vue/new-line-between-multi-line-property": "off",
        "vue/next-tick-style": "error",
        "vue/no-bare-strings-in-template": [
          "error",
          {
            "allowlist": [
              "Loading...",
              "*",
              "Error!"
            ]
          }
        ],
        "vue/no-boolean-default": "error",
        "vue/no-duplicate-attr-inheritance": "error",
        "vue/no-empty-component-block": "error",
        "vue/no-invalid-model-keys": "error",
        "vue/no-multiple-objects-in-class": "error",
        "vue/no-potential-component-option-typo": "error",
        "vue/no-reserved-component-names": "error",
        "vue/no-restricted-block": "error",
        "vue/no-restricted-call-after-await": "error",
        "vue/no-restricted-component-options": "error",
        "vue/no-restricted-custom-event": "off",
        "vue/no-restricted-props": "off",
        "vue/no-restricted-static-attribute": "off",
        "vue/no-restricted-v-bind": "off",
        "vue/no-static-inline-styles": "error",
        "vue/no-template-target-blank": "error",
        "vue/no-this-in-before-route-enter": "error",
        "vue/no-unregistered-components": "off", // Vue Class Components are false positive.
        "vue/no-unsupported-features": "error",
        "vue/no-unused-properties": [
          "error",
          {
            "groups": [ "props" ],
            "deepData": true,
            "ignorePublicMembers": false
          }
        ],
        "vue/no-unused-refs": "error",
        "vue/no-useless-v-bind": "error",
        "vue/padding-line-between-blocks": "warn",
        "vue/require-direct-export": "off", // Vue Class Components are false positive.
        "vue/require-emit-validator": "error",
        "vue/require-expose": "error",
        "vue/require-name-property": "error",
        "vue/script-indent": [
          "error",
          "tab"
        ],
        "vue/sort-keys": "off",
        "vue/static-class-names-order": "off",
        "vue/v-for-delimiter-style": "error",
        "vue/v-on-event-hyphenation": "error",
        "vue/v-on-function-call": [
          "error",
          "never"
        ],
        "vue/array-bracket-newline": "off",
        "vue/arrow-spacing": "error",
        "vue/block-spacing": "error",
        "vue/brace-style": "error",
        "vue/camelcase": "warn",
        "vue/comma-dangle": [ "error", "never" ],
        "vue/comma-spacing": "error",
        "vue/comma-style": "error",
        "vue/dot-location": [ "error", "property" ],
        "vue/dot-notation": "off",
        "vue/eqeqeq": "error",
        "vue/func-call-spacing": "error",
        "vue/key-spacing": "error",
        "vue/keyword-spacing": "error",
        "vue/max-len": [
          "error",
          {
            "code": 120,
            "ignoreComments": true
          }
        ],
        "vue/no-constant-condition": "error",
        "vue/no-empty-pattern": "warn",
        "vue/no-extra-parens": "error",
        "vue/no-irregular-whitespace": "error",
        "vue/no-restricted-syntax": "off",
        "vue/no-sparse-arrays": "error",
        "vue/no-useless-concat": "error",
        "vue/object-curly-newline": "off",
        "vue/object-property-newline": [
          "error",
          { "allowAllPropertiesOnSameLine": true }
        ],
        "vue/operator-linebreak": "off",
        "vue/prefer-template": "error",
        "vue/space-in-parens": "error",
        "vue/space-infix-ops": "off",
        "vue/space-unary-ops": "error",
        "vue/template-curly-spacing": "error"
      }
    }
  ]
}